name: SonarQube Scan & Deploy to AWS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies (jq, curl, unzip)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl unzip

      - name: Start SonarQube (Docker)
        run: |
          if [ "$(docker ps -aq -f name=sonarqube)" ]; then
            echo "SonarQube container already exists. Restarting..."
            docker start sonarqube
          else
            echo "Pulling and running SonarQube..."
            docker pull sonarqube:lts
            docker run -d --name sonarqube -p 9000:9000 sonarqube:lts
          fi
          
          echo "Waiting for SonarQube to be ready..."
          for i in {1..30}; do
            STATUS=$(curl -s http://localhost:9000/api/system/status | jq -r '.status' || echo "DOWN")
            if [[ "$STATUS" == "UP" ]]; then
              echo "✅ SonarQube is ready!"
              break
            fi
            echo "⏳ Waiting for SonarQube to start... ($i/30)"
            sleep 10
          done

      - name: Install SonarQube Scanner
        run: |
          wget -O sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.0.1.3006-linux.zip
          unzip sonar-scanner.zip
          sudo mv sonar-scanner-5.0.1.3006-linux /opt/sonar-scanner
          echo "export PATH=/opt/sonar-scanner/bin:$PATH" >> ~/.bashrc
          echo "export PATH=/opt/sonar-scanner/bin:$PATH" >> ~/.profile
          source ~/.bashrc
          source ~/.profile

      - name: Verify SonarScanner Installation
        run: |
          export PATH="/opt/sonar-scanner/bin:$PATH"
          sonar-scanner --version || { echo "❌ SonarScanner not found! Exiting pipeline."; exit 1; }

      - name: Check SonarQube Status
        run: |
          STATUS=$(curl -s http://localhost:9000/api/system/status | jq -r '.status' || echo "DOWN")
          echo "SonarQube Status: $STATUS"
          if [[ "$STATUS" != "UP" ]]; then
            echo "❌ SonarQube is not running! Exiting pipeline."
            exit 1
          fi

      - name: Validate SonarQube Login
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          RESPONSE=$(curl -s -u "$SONAR_TOKEN:" http://localhost:9000/api/authentication/validate | jq -r '.valid')
          if [[ "$RESPONSE" != "true" ]]; then
            echo "❌ Authentication failed! Check SonarQube token."
            exit 1
          else
            echo "✅ Authentication successful."
          fi
            - name: Run SonarQube Scan
        run: |
          docker run --rm \
            -e "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}" \
            -e "SONAR_TOKEN=${{ secrets.SONAR_TOKEN }}" \
            -v "${{ github.workspace }}:/usr/src" \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey="gittos3" \
            -Dsonar.sources="." \
            -Dsonar.host.url="${{ secrets.SONAR_HOST_URL }}" \
            -Dsonar.login="${{ secrets.SONAR_TOKEN }}"

      - name: Check SonarQube Quality Gate
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sleep 10
          STATUS=$(curl -s -H "Authorization: Bearer $SONAR_TOKEN" "http://localhost:9000/api/qualitygates/project_status?projectKey=gittos3" | jq -r '.projectStatus.status')
          echo "SonarQube Quality Gate Status: $STATUS"
          if [[ "$STATUS" != "OK" ]]; then
            echo "❌ Security vulnerabilities found! Stopping pipeline."
            exit 1
          fi

  deploy_to_aws:
    needs: sonar_scan  # Runs only if SonarQube scan passes
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: us-east-1

      - name: Trigger AWS CodePipeline
        run: |
          aws codepipeline start-pipeline-execution --name MyAWSCodePipeline
